# Generated by Django 4.2.1 on 2023-05-13 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artyweb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Formateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=255)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='')),
                ('domaine', models.CharField(choices=[('DG', 'Design Graphique'), ('DW', 'Design Web'), ('SC', 'Scénarisation')], max_length=2)),
                ('rating', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('photo', models.ImageField(upload_to='')),
                ('description', models.TextField()),
                ('datedebut', models.DateField()),
                ('datefin', models.DateField()),
                ('nbheure_semaine', models.IntegerField()),
                ('lienmeet', models.URLField()),
                ('formateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='artyweb.formateur')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='artyweb.service')),
            ],
        ),
    ]
