# Generated by Django 4.2.1 on 2023-05-14 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artyweb', '0002_formateur_formation'),
    ]

    operations = [
        migrations.AddField(
            model_name='formation',
            name='prix',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
