# Generated by Django 4.2.1 on 2023-05-14 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artyweb', '0003_formation_prix'),
    ]

    operations = [
        migrations.CreateModel(
            name='Panier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('quantite', models.IntegerField(default=1)),
                ('formation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artyweb.formation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artyweb.client')),
            ],
        ),
    ]
