# Generated by Django 4.2.1 on 2023-05-14 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artyweb', '0004_panier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='panier',
            name='formation',
        ),
        migrations.AddField(
            model_name='panier',
            name='formations',
            field=models.ManyToManyField(related_name='paniers', to='artyweb.formation'),
        ),
    ]
