# Generated by Django 4.2.1 on 2023-05-14 11:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('artyweb', '0005_remove_panier_formation_panier_formations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='panier',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
